#!/usr/bin/env bash

set -e

# copy list of all packages installed with apt
comm -23 <(apt-mark showmanual | sort -u) <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u) > apt_packages

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# dotbot vars
DOTBOT_DIR="${BASEDIR}/dotbot"
DOTBOT_BIN="${DOTBOT_DIR}/bin/dotbot"
DOTBOT_CONFIG="${BASEDIR}/install.conf.yaml"

# submodule sync
git -C $BASEDIR submodule sync --recursive
git -C $BASEDIR submodule update --init --recursive

# dotbot install
"${DOTBOT_BIN}" -d "${BASEDIR}" -c "${DOTBOT_CONFIG}" "${@}"
