#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export DOTFILES="${DOTFILES:-$BASEDIR}"

# dotbot vars
DOTBOT_DIR="${DOTFILES}/dotbot"
DOTBOT_BIN="${DOTBOT_DIR}/bin/dotbot"
DOTBOT_CONFIG="${DOTFILES}/install.conf.yaml"

# submodule sync
git -C $DOTFILES submodule sync --recursive
git -C $DOTFILES submodule update --init --recursive

# dotbot install
"${DOTBOT_BIN}" -d "${DOTFILES}" -c "${DOTBOT_CONFIG}" "${@}"
